language: go

go:
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - tip

 
env:
  global:
    - PGUSER=postgres
    - PQGOSSLTESTS=1

  matrix:
    - PGVERSION=9.4
    - PGVERSION=9.3
    - PGVERSION=9.2
    - PGVERSION=9.1
    - PGVERSION=9.0
    - PGVERSION=8.4

script:
 - go test -v ./...

before_script:
 - make structure
 - make fixtures 