language: go
go:
  - 1.4
  - tip
env:
  global:
    - PGUSER=postgres
    - PQGOSSLTESTS=1
    - USRMNG_DBNAME=usermanager
    - USRMNG_USER=postgres
  matrix:
    - PGVERSION=9.4
addons:
  postgresql: "9.4"

script:
 - psql usermanager -f ./usermanager.sql -U postgres
 - psql usermanager -f ./fixtures.sql -U postgres
 - $HOME/gopath/bin/goveralls -service=travis-ci

before_script:
 - go get github.com/axw/gocov/gocov
 - go get github.com/mattn/goveralls
 - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
 - go get github.com/tools/godep
 - psql -c 'create database usermanager' -U postgres
