language: go
go:
  - 1.4
  - tip
env:
  global:
    - PGUSER=postgres
    - PQGOSSLTESTS=1
    - USRMNG_DBNAME=usermanager
  matrix:
    - PGVERSION=9.3
script:
 - go test -v ./...

before_script:
 - go get github.com/tools/godep
 - psql -c 'create database usermanager' -U postgres
 - psql usermanager -f usermanager.sql -U postgres
 - psql usermanager -f fixtures.sql -U postgres
